// ─── SEO CHANGE: robots.txt generated by Next.js App Router ─────────────────
// This file auto-generates /robots.txt at build time.
// Update SITE_URL if the domain changes.

import { MetadataRoute } from "next";

const SITE_URL = "https://www.kineticprofitness.com";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        // ── Block pages that should NOT be indexed ───────────────────────
        disallow: ["/landing/", "/enroll/", "/api/"],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
  };
}
