export const programs = [
  {
    slug: "nutrition-mastery",
    title: "Nutrition Mastery",
    subtitle: "Understand food science and transform your eating forever",
    icon: "🥗",
    duration: "6 Weeks",
    level: "All Levels",
    price: 7999,
    originalPrice: 11999,
    tag: "Science-Based",
    color: "#4CAF50",
    image: "/images/nutrition-mastery.jpg",
    description: "Stop following fad diets and start understanding the science of nutrition. This program gives you the knowledge and tools to make smart food choices for life — not just for 6 weeks.",
    highlights: ["Macro & micronutrient mastery", "Meal planning templates", "Grocery guides & food labels", "Supplement science module", "Gut health protocol", "Ongoing Q&A access"],
    curriculum: [
      { week: "Week 1", title: "Nutrition Foundations", desc: "Macros, micros, calories — understand what your body actually needs." },
      { week: "Week 2", title: "Food Science", desc: "How food affects hormones, energy, metabolism and performance." },
      { week: "Week 3-4", title: "Meal Planning", desc: "Build your personalised meal plan with templates and portion guides." },
      { week: "Week 5-6", title: "Lifestyle Integration", desc: "Eating out, social events, travel — make nutrition sustainable forever." },
    ],
    testimonial: { quote: "For the first time I understand WHY I'm eating what I'm eating. Life changing.", name: "Anjali M.", result: "Lost 8kg, gained energy" },
  },
  {
    slug: "fitness-trainer-certification",
    title: "Fitness Trainer Certification",
    subtitle: "Become a certified fitness professional — career-ready in 6 weeks",
    icon: "🎓",
    duration: "6 Weeks",
    level: "Beginner–Advanced",
    price: 14999,
    originalPrice: 22999,
    tag: "Career Track",
    color: "#2196F3",
    image: "/images/fitness-certification.jpg",
    description: "India's most practical PT certification. Learn anatomy, programming, client coaching — everything to start your fitness career at top gyms or build your own online coaching business.",
    highlights: ["Exercise science & anatomy", "Program design & periodization", "Client assessment tools", "Business of fitness module", "Live sessions with Shraddha", "KPF Academy Certificate"],
    curriculum: [
      { week: "Module 1", title: "Exercise Science", desc: "Anatomy, physiology and biomechanics for fitness professionals." },
      { week: "Module 2", title: "Nutrition Science", desc: "Sports nutrition, meal planning and dietary assessment." },
      { week: "Module 3", title: "Program Design", desc: "Design effective programs for different goals and populations." },
      { week: "Module 4", title: "Professional Practice", desc: "Client management, assessment and building your fitness career." },
    ],
    testimonial: { quote: "This course gave me the knowledge and confidence to start my own coaching practice.", name: "Rohan K.", result: "Now a certified coach" },
  },
];

export const workshops = [
  {
    slug: "nutrition-masterclass",
    title: "Nutrition Masterclass",
    date: "Every Saturday",
    duration: "3 Hours",
    price: 1999,
    mode: "Online & In-Person",
    desc: "A deep-dive into evidence-based nutrition with Shraddha Gadit. Learn what actually works, what doesn't and why.",
    spots: 20,
  },
  {
    slug: "fat-loss-workshop",
    title: "Fat Loss Blueprint Workshop",
    date: "2nd Sunday of Month",
    duration: "4 Hours",
    price: 2499,
    mode: "Online",
    desc: "The complete fat loss system in one intensive workshop. Leave with a personalised plan ready to execute.",
    spots: 30,
  },
  {
    slug: "mindset-performance",
    title: "Mindset & Performance",
    date: "Last Friday of Month",
    duration: "2 Hours",
    price: 1499,
    mode: "Online",
    desc: "Mental performance, habit science and the psychology of lasting change. A workshop that transforms your mindset.",
    spots: 50,
  },
];

export const blogPosts = [
  {
    slug: "science-of-fat-loss",
    title: "The Real Science of Fat Loss (That No One Talks About)",
    category: "Nutrition",
    date: "March 10, 2026",
    readTime: "8 min read",
    excerpt: "Forget everything fad diets told you. Here's what the science actually says about losing fat sustainably and keeping it off forever.",
    content: "Fat loss is one of the most misunderstood topics in the fitness industry. The internet is flooded with conflicting advice — keto, intermittent fasting, calorie counting, cleanses. But what does the science actually say?\n\nAt its core, fat loss comes down to one principle: a sustained caloric deficit. When your body consistently burns more energy than it consumes, it turns to stored fat as fuel. This is not negotiable — it is basic thermodynamics.\n\nHowever, the quality of your deficit matters enormously. A deficit created by crash dieting leads to muscle loss, metabolic adaptation and rebound weight gain. A deficit created through strategic nutrition and progressive training preserves muscle, keeps your metabolism elevated and produces lasting results.\n\nThe three pillars of sustainable fat loss are: adequate protein intake (at least 1.6g per kg of bodyweight), progressive resistance training to preserve muscle mass, and a moderate caloric deficit of 300-500 calories per day.\n\nShraddha Gadit and the KPF Academy approach every fat loss program with this evidence-based foundation — which is why our clients get results that last.",
  },
  {
    slug: "protein-myths-busted",
    title: "5 Protein Myths That Are Sabotaging Your Results",
    category: "Nutrition",
    date: "March 3, 2026",
    readTime: "6 min read",
    excerpt: "Too much protein damages your kidneys? You can only absorb 30g at a time? Let's bust the most common protein myths with actual science.",
    content: "Protein is arguably the most important macronutrient for body composition, yet it's also the most misunderstood. Here are five myths we hear constantly at KPF Academy — and what the science actually says.\n\nMyth 1: High protein damages your kidneys. This myth is only relevant for people with pre-existing kidney disease. For healthy individuals, high protein diets have shown no negative effects on kidney function in multiple large studies.\n\nMyth 2: You can only absorb 30g of protein per meal. Your body can absolutely absorb more than 30g of protein in a single meal — it just does so more slowly. Total daily protein intake matters far more than per-meal amounts.\n\nMyth 3: Plant protein is inferior to animal protein. While animal proteins tend to have better amino acid profiles, you can absolutely meet all your protein needs through plant sources with thoughtful food combining.\n\nMyth 4: You need protein immediately after training. The post-workout anabolic window is much wider than the fitness industry suggests — typically 4-6 hours. Total daily protein intake is what drives results.\n\nMyth 5: More protein always means more muscle. Beyond approximately 2.2g per kg of bodyweight, additional protein shows diminishing returns. Progressive training stimulus is the primary driver of muscle growth.",
  },
  {
    slug: "sleep-and-fitness",
    title: "Why Sleep Is Your Most Powerful Fitness Tool",
    category: "Wellness",
    date: "February 24, 2026",
    readTime: "7 min read",
    excerpt: "You can have the perfect training program and diet, but if your sleep is poor, you're leaving 50% of your results on the table.",
    content: "In 17 years of coaching, the single most underrated factor in fitness results is sleep. We obsess over training programs and nutrition plans, but consistently overlook the 7-9 hours that determine whether all that hard work actually pays off.\n\nDuring deep sleep, your body releases growth hormone — the primary driver of muscle repair and fat metabolism. Poor sleep suppresses growth hormone secretion by up to 70%, meaning your muscles recover slower and your fat-burning capacity is significantly diminished.\n\nSleep deprivation also dramatically affects hunger hormones. Ghrelin (the hunger hormone) increases by 28% with poor sleep, while leptin (the satiety hormone) decreases by 18%. This is why you feel hungrier and crave higher-calorie foods when you're sleep deprived.\n\nFor optimal fitness results, prioritise: consistent sleep and wake times (even on weekends), a cool, dark bedroom environment (18-20°C is optimal), no screens 60 minutes before bed, and no caffeine after 2pm.\n\nAt KPF Academy, sleep optimisation is a core part of every coaching program — because without it, you're building on sand.",
  },
  {
    slug: "strength-training-women",
    title: "Why Every Woman Should Strength Train",
    category: "Training",
    date: "February 17, 2026",
    readTime: "5 min read",
    excerpt: "Strength training won't make you bulky — it will make you strong, confident and metabolically powerful. Here's the science.",
    content: "One of the most persistent and damaging myths in women's fitness is that strength training will make you look bulky or masculine. This myth has kept millions of women away from the training modality that would benefit them most.\n\nThe reality: women have approximately 15-20 times less testosterone than men. This hormonal difference makes it physiologically very difficult for women to build the kind of muscle mass associated with a bulky appearance. What strength training actually does for women is build lean, defined muscle, dramatically increase metabolic rate, improve bone density (crucial for preventing osteoporosis), enhance posture, and build functional strength for everyday life.\n\nResearch consistently shows that women who strength train have better body composition outcomes than those who do cardio alone — they lose more fat, maintain more muscle and have higher resting metabolic rates.\n\nAt KPF Academy, all of our programs — for men and women — are built on a foundation of progressive resistance training, because the science is unambiguous: it is the most effective tool for body composition, health and longevity.",
  },
];

export const testimonials = [
  { name: "Priya Sharma", location: "Mumbai", program: "Nutrition Mastery", result: "Lost 14kg", period: "8 weeks", quote: "I had tried everything — keto, intermittent fasting, crash diets. Nothing worked long term. KPF Academy's approach is completely different. Shraddha taught me the science, not just the rules. I lost 14kg and I've kept it off for 6 months.", rating: 5 },
  { name: "Rahul Desai", location: "Pune", program: "Fitness Trainer Certification", result: "Now a certified trainer", period: "6 weeks", quote: "The programming is unlike anything I've followed before. I now run my own coaching practice and earn from fitness full-time.", rating: 5 },
  { name: "Anjali Mehta", location: "Bangalore", program: "Nutrition Mastery", result: "Transformed relationship with food", period: "6 weeks", quote: "This course changed how I think about food entirely. No more guilt, no more confusion. Just clear science-backed principles that I can follow for life.", rating: 5 },
  { name: "Vikram Rao", location: "Delhi", program: "Fitness Trainer Certification", result: "Complete transformation", period: "6 weeks", quote: "Working with Shraddha's system is an experience unlike any other. The attention to detail, the adjustments week by week, the support — it's worth every rupee.", rating: 5 },
  { name: "Neha Kapoor", location: "Mumbai", program: "Nutrition Mastery", result: "Better energy, zero confusion", period: "6 weeks", quote: "I came in completely lost about food. I leave with a lifetime framework that works for me. Genuinely life-changing.", rating: 5 },
  { name: "Arjun Nair", location: "Chennai", program: "Fitness Trainer Certification", result: "Became a certified coach", period: "Self-paced", quote: "The knowledge in this course is incredible. I've read textbooks that don't cover what Shraddha covers. I now run my own coaching practice.", rating: 5 },
];

export const pricingPlans = [
  {
    name: "NUTRITION",
    price: 7999,
    period: "one-time",
    desc: "Master the science of nutrition and transform how you eat — for life.",
    features: ["Full Nutrition Mastery program", "Meal planning templates", "Macro & micronutrient guides", "Supplement science module", "Gut health protocol", "Ongoing Q&A access", "Certificate on completion"],
    cta: "Enroll in Nutrition",
    highlight: false,
    slug: "nutrition-mastery",
  },
  {
    name: "TRAINER CERTIFICATION",
    price: 14999,
    period: "one-time",
    desc: "Become a certified fitness professional and start your career in fitness.",
    features: ["Fitness Trainer Certification", "Exercise science & anatomy", "Program design mastery", "Client assessment tools", "Live sessions with Shraddha", "Business of fitness module", "KPF Academy Certificate", "Placement support"],
    cta: "Get Certified",
    highlight: true,
    tag: "Career Track",
    slug: "fitness-trainer-certification",
  },
  {
    name: "BUNDLE",
    price: 19999,
    period: "one-time",
    desc: "Both programs together — become a complete fitness & nutrition professional.",
    features: ["Everything in Nutrition Mastery", "Everything in Trainer Certification", "Priority support access", "Combo certificate", "Bonus: Business of Coaching module", "Lifetime community access"],
    cta: "Get Both Programs",
    highlight: false,
    slug: "fitness-trainer-certification",
  },
];
